[package]
name = "frontend"
version.workspace = true
edition.workspace = true

[[bin]]
name = "checkers-client"
path = "src/bin/main.rs"

[lib]
name = "checkers_client_lib"
path = "src/lib.rs"

[dependencies]
console_error_panic_hook = "0.1.7"
gloo-net = "0.6.0"
log = "0.4.29"
wasm-bindgen-futures = "0.4.58"
wasm-logger = "0.2.0"
yew = { version = "0.22.0", features = ["csr"] }
