[package]
name = "backend"
version.workspace = true
edition.workspace = true

[[bin]]
name = "server"
path = "src/bin/main.rs"

[lib]
name = "rusty_checkers_server_lib"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.42"
config = "0.15.19"
rama = { git = "https://github.com/plabayo/rama.git", tag = "rama-0.3.0-alpha.4", features = [ "http-full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-aux = "4.7.0"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["full"] }
tracing-bunyan-formatter = "0.3.10"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.22"
uuid = "1.19.0"


[profile.release]
lto = true         
codegen-units = 1   
strip = true        
panic = "abort"     

[profile.dev]
debug = true        

[profile.dev.package."*"]
opt-level = 2
